modLoader="javafml"
loaderVersion="[43,)"
license="Not specified"

[[mods]]
modId="trumpcraft"
version="5.0.2.0"
displayName="Trumpcraft"
credits="Derex"
displayURL="https://www.curseforge.com/minecraft/mc-mods/trumpcraft"
logoFile="logo.png"
authors="Derex"
description="We'll make Minecraft great again"

[[dependencies.trumpcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




